### ISSUE TITLE
Document Quest VPN connection strategy

### ISSUE THREAD

**Issue by parseccentric** [gelic-idealab/komodo-relay#6]
And also diagnose whether Quest can connect over non-VPN without running into alone-on-entry / doesn't-receive-any-calls-problem. 

Also diagnose whether mobile devices can route Quest traffic through VPN properly.

**Comment by parseccentric** [comment]
@wallacerob   Unfortunately, this article says that sharing a WiFi connection from a Mac is not possible without purchasing an external adapter.  So you can only share an ethernet connection. 

> In cases in which only Wi-Fi is available and you’re trying to share that, Apple prevents sharing Wi-Fi over Wi-Fi, because Macs lack the built-in ability to operate two separately named networks on the same hardware. (This is technically possible: it’s called VLAN for virtual LAN, and it’s used widely in corporate and large-scale public Wi-Fi deployments.)

https://www.macworld.com/article/3546239/how-to-share-a-wi-fi-connection-via-macos.html

**Comment by wallacerob** [comment]
> @wallacerob Unfortunately, this article says that sharing a WiFi connection from a Mac is not possible without purchasing an external adapter. So you can only share an ethernet connection.
> 
yeah, i'm also running into problems sharing on Windows, even with the VPN on Ethernet.
